/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bases2;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Karen Medina
 */
public class Main_Productos extends javax.swing.JFrame {

    /**
     * Creates new form Main_Productos
     */
    public Main_Productos() {
        initComponents();
        Main_Farmacia abrir = new Main_Farmacia();
        abrir.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_protegido = new javax.swing.ButtonGroup();
        jd_FarmaciaCasa = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rb_siCasa = new javax.swing.JRadioButton();
        rb_noCasa = new javax.swing.JRadioButton();
        tf_identificaCasa = new javax.swing.JTextField();
        tf_nombreCasa = new javax.swing.JTextField();
        tf_fabricanteCasa = new javax.swing.JTextField();
        tf_pCostoCasa = new javax.swing.JTextField();
        tf_pVentaCasa = new javax.swing.JTextField();
        js_unidadesCasa = new javax.swing.JSpinner();
        btn_AgregarFCasa = new javax.swing.JButton();
        jd_Cosmetica = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_AgregarCosmetica = new javax.swing.JButton();
        tf_idCosmetica = new javax.swing.JTextField();
        tf_nomCosmetica = new javax.swing.JTextField();
        tf_fCosmetica = new javax.swing.JTextField();
        tf_pcCosmetica = new javax.swing.JTextField();
        tf_pvCosmetica = new javax.swing.JTextField();
        js_unidCosmetica = new javax.swing.JSpinner();
        rb_siCosmetica = new javax.swing.JRadioButton();
        rb_noCosmetica = new javax.swing.JRadioButton();
        jd_Higiene = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_idHigiene = new javax.swing.JTextField();
        tf_nomHigiene = new javax.swing.JTextField();
        tf_fHigiene = new javax.swing.JTextField();
        tf_pcHigiene = new javax.swing.JTextField();
        tf_pvHigiene = new javax.swing.JTextField();
        js_unidHigiene = new javax.swing.JSpinner();
        rb_siHigiene = new javax.swing.JRadioButton();
        rb_noHigiene = new javax.swing.JRadioButton();
        btn_agregarHigiene = new javax.swing.JButton();
        jd_Infantil = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tf_idInfantil = new javax.swing.JTextField();
        tf_nomInfantil = new javax.swing.JTextField();
        tf_fInfantil = new javax.swing.JTextField();
        tf_pcInfantil = new javax.swing.JTextField();
        tf_pvInfantil = new javax.swing.JTextField();
        js_unidInfantil = new javax.swing.JSpinner();
        rb_siInfantil = new javax.swing.JRadioButton();
        js_noInfantil = new javax.swing.JRadioButton();
        btn_agregarInfantil = new javax.swing.JButton();
        bg_farmaciaCasa = new javax.swing.ButtonGroup();
        bg_cosmetica = new javax.swing.ButtonGroup();
        bg_higiene = new javax.swing.ButtonGroup();
        bg_infantil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Casa = new javax.swing.JButton();
        btn_Cosmetica = new javax.swing.JButton();
        btn_Infantil = new javax.swing.JButton();
        btn_Higiene = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Producto Farmacia Casa");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Identificación:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Nombre: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Fabricante:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Precio Costo:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Precio Venta:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Unidades:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("¿Está protegido?");

        bg_farmaciaCasa.add(rb_siCasa);
        rb_siCasa.setText("Si");

        bg_farmaciaCasa.add(rb_noCasa);
        rb_noCasa.setSelected(true);
        rb_noCasa.setText("No");

        js_unidadesCasa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btn_AgregarFCasa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_AgregarFCasa.setText("Agregar");
        btn_AgregarFCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarFCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(41, 41, 41)
                                .addComponent(js_unidadesCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(22, 22, 22)
                                .addComponent(tf_pCostoCasa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_identificaCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(tf_fabricanteCasa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombreCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tf_pVentaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(rb_siCasa)
                        .addGap(18, 18, 18)
                        .addComponent(rb_noCasa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AgregarFCasa)
                .addGap(191, 191, 191))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(tf_identificaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_fabricanteCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_pCostoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_pVentaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(js_unidadesCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rb_siCasa)
                    .addComponent(rb_noCasa))
                .addGap(36, 36, 36)
                .addComponent(btn_AgregarFCasa)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_FarmaciaCasaLayout = new javax.swing.GroupLayout(jd_FarmaciaCasa.getContentPane());
        jd_FarmaciaCasa.getContentPane().setLayout(jd_FarmaciaCasaLayout);
        jd_FarmaciaCasaLayout.setHorizontalGroup(
            jd_FarmaciaCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_FarmaciaCasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_FarmaciaCasaLayout.setVerticalGroup(
            jd_FarmaciaCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_FarmaciaCasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Producto Cosmética");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Identificación:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Nombre:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Fabricante:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Precio Costo:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Precio Venta:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Unidades:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("¿Está protegido?");

        btn_AgregarCosmetica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_AgregarCosmetica.setText("Agregar");
        btn_AgregarCosmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarCosmeticaActionPerformed(evt);
            }
        });

        js_unidCosmetica.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        bg_cosmetica.add(rb_siCosmetica);
        rb_siCosmetica.setText("Si");

        bg_cosmetica.add(rb_noCosmetica);
        rb_noCosmetica.setSelected(true);
        rb_noCosmetica.setText("No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(rb_siCosmetica)
                        .addGap(18, 18, 18)
                        .addComponent(rb_noCosmetica)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(js_unidCosmetica, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(tf_idCosmetica)
                            .addComponent(tf_fCosmetica)
                            .addComponent(tf_pcCosmetica, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(tf_pvCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nomCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_AgregarCosmetica)
                        .addGap(138, 138, 138))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_idCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tf_nomCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_fCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_pcCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(tf_pvCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(js_unidCosmetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(rb_siCosmetica)
                    .addComponent(rb_noCosmetica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_AgregarCosmetica)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jd_CosmeticaLayout = new javax.swing.GroupLayout(jd_Cosmetica.getContentPane());
        jd_Cosmetica.getContentPane().setLayout(jd_CosmeticaLayout);
        jd_CosmeticaLayout.setHorizontalGroup(
            jd_CosmeticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CosmeticaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_CosmeticaLayout.setVerticalGroup(
            jd_CosmeticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CosmeticaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Producto Higiene");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Identificación:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Nombre:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Fabricante:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Precio costo:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Precio venta:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Unidades:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("¿Está protegido?");

        js_unidHigiene.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        bg_higiene.add(rb_siHigiene);
        rb_siHigiene.setText("Si");

        bg_higiene.add(rb_noHigiene);
        rb_noHigiene.setSelected(true);
        rb_noHigiene.setText("No");

        btn_agregarHigiene.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_agregarHigiene.setText("Agregar");
        btn_agregarHigiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarHigieneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_fHigiene)
                            .addComponent(tf_idHigiene)
                            .addComponent(tf_pcHigiene)
                            .addComponent(js_unidHigiene, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_pvHigiene, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(tf_nomHigiene)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(29, 29, 29)
                        .addComponent(rb_siHigiene)
                        .addGap(18, 18, 18)
                        .addComponent(rb_noHigiene)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_agregarHigiene)
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_idHigiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tf_nomHigiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_fHigiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_pcHigiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(tf_pvHigiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(js_unidHigiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(rb_siHigiene)
                    .addComponent(rb_noHigiene))
                .addGap(36, 36, 36)
                .addComponent(btn_agregarHigiene)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_HigieneLayout = new javax.swing.GroupLayout(jd_Higiene.getContentPane());
        jd_Higiene.getContentPane().setLayout(jd_HigieneLayout);
        jd_HigieneLayout.setHorizontalGroup(
            jd_HigieneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_HigieneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_HigieneLayout.setVerticalGroup(
            jd_HigieneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_HigieneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Producto Infantil");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("Identificación:");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Nombre:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Fabricante:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Precio costo:");
        jLabel38.setToolTipText("");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setText("Precio venta:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setText("Unidades:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("¿Está protegido?");

        js_unidInfantil.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        bg_infantil.add(rb_siInfantil);
        rb_siInfantil.setText("Si");

        bg_infantil.add(js_noInfantil);
        js_noInfantil.setSelected(true);
        js_noInfantil.setText("No");

        btn_agregarInfantil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_agregarInfantil.setText("Agregar");
        btn_agregarInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarInfantilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel40))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_idInfantil)
                                            .addComponent(tf_fInfantil, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel36))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(tf_pcInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(jLabel39)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_pvInfantil, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(tf_nomInfantil)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(js_unidInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(28, 28, 28)
                        .addComponent(rb_siInfantil)
                        .addGap(18, 18, 18)
                        .addComponent(js_noInfantil)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_agregarInfantil)
                        .addGap(192, 192, 192))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_idInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(tf_nomInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_fInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(tf_pvInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pcInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_unidInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(rb_siInfantil)
                    .addComponent(js_noInfantil))
                .addGap(32, 32, 32)
                .addComponent(btn_agregarInfantil)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_InfantilLayout = new javax.swing.GroupLayout(jd_Infantil.getContentPane());
        jd_Infantil.getContentPane().setLayout(jd_InfantilLayout);
        jd_InfantilLayout.setHorizontalGroup(
            jd_InfantilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InfantilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_InfantilLayout.setVerticalGroup(
            jd_InfantilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InfantilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_Casa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Casa.setText("Farmacia casa");
        btn_Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CasaActionPerformed(evt);
            }
        });

        btn_Cosmetica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Cosmetica.setText("Cosmética");
        btn_Cosmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CosmeticaActionPerformed(evt);
            }
        });

        btn_Infantil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Infantil.setText("Infantil");
        btn_Infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InfantilActionPerformed(evt);
            }
        });

        btn_Higiene.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Higiene.setText("Higiene");
        btn_Higiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HigieneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Casa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cosmetica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Infantil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Higiene, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_Casa)
                .addGap(18, 18, 18)
                .addComponent(btn_Cosmetica)
                .addGap(18, 18, 18)
                .addComponent(btn_Infantil)
                .addGap(18, 18, 18)
                .addComponent(btn_Higiene)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CasaActionPerformed
        jd_FarmaciaCasa.pack();
        //jd_FarmaciaCasa.setModal(true);
        jd_FarmaciaCasa.setVisible(true);
    }//GEN-LAST:event_btn_CasaActionPerformed

    private void btn_CosmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CosmeticaActionPerformed
        jd_Cosmetica.pack();
        //jd_Cosmetica.setModal(true);
        jd_Cosmetica.setVisible(true);
    }//GEN-LAST:event_btn_CosmeticaActionPerformed

    private void btn_InfantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InfantilActionPerformed
        jd_Infantil.pack();
        //jd_Infantil.setModal(true);
        jd_Infantil.setVisible(true);
    }//GEN-LAST:event_btn_InfantilActionPerformed

    private void btn_HigieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HigieneActionPerformed
        jd_Higiene.pack();
        //jd_Higiene.setModal(true);
        jd_Higiene.setVisible(true);
    }//GEN-LAST:event_btn_HigieneActionPerformed

    private void btn_AgregarFCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarFCasaActionPerformed
        String id, nom, fabrica,tip;
        double pCoste, pVenta;
        boolean esta = false;
        int unid;

        id = tf_identificaCasa.getText();
        nom = tf_nombreCasa.getText();
        fabrica = tf_fabricanteCasa.getText();
        pCoste = Double.parseDouble(tf_pCostoCasa.getText());
        pVenta = Double.parseDouble(tf_pVentaCasa.getText());
        unid = (int) js_unidadesCasa.getValue();

        if (rb_siCasa.isSelected()) {
            esta = true;
            rb_noCasa.setVisible(false);
        }
        if (rb_noCasa.isSelected()) {
            esta = true;
            rb_siCasa.setVisible(false);
        }
        
        tip="Farmacia_Casa";
                
        prod_fCasa.add(new Prod_FarmaciaCasa(tip,id, nom, fabrica, pCoste, pVenta, unid, esta));
        prod.add(new Productos(id, nom, fabrica, pCoste, pVenta, unid, esta));
        System.out.println(prod);
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for (int i = 0; i < prod_fCasa.size(); i++) {
            modelo.addElement(prod_fCasa.get(i).getNombre());
        }
        Main_Farmacia.cb_pFC.setModel(modelo);
        
        JOptionPane.showMessageDialog(this, "Se agregó");
        
        tf_identificaCasa.setText("");
        tf_nombreCasa.setText("");
        tf_fabricanteCasa.setText("");
        tf_pCostoCasa.setText("");
        tf_pVentaCasa.setText("");
        rb_noCasa.setSelected(true);
        rb_siCasa.setSelected(false);
        js_unidadesCasa.setValue(0);
    }//GEN-LAST:event_btn_AgregarFCasaActionPerformed

    private void btn_AgregarCosmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarCosmeticaActionPerformed
        String id2, nom2, fabrica2, tip2;
        double pCoste2, pVenta2;
        boolean esta2 = false;
        int unid2;

        id2 = tf_idCosmetica.getText();
        nom2 = tf_nomCosmetica.getText();
        fabrica2 = tf_fCosmetica.getText();
        pCoste2 = Double.parseDouble(tf_pcCosmetica.getText());
        pVenta2 = Double.parseDouble(tf_pvCosmetica.getText());
        unid2 = (int) js_unidCosmetica.getValue();

        if (rb_siCosmetica.isSelected()) {
            esta2 = true;
            rb_noCosmetica.setVisible(false);
        }
        if (rb_noCosmetica.isSelected()) {
            esta2 = true;
            rb_siCosmetica.setVisible(false);
        }
        
        tip2="Cosmetica";
        
        prod__Cosmet.add(new Prod_Cosmetica(tip2, id2, nom2, fabrica2, pCoste2, pVenta2, unid2, esta2));
        prod.add(new Productos(id2, nom2, fabrica2, pCoste2, pVenta2, unid2, esta2));
        System.out.println(prod);
        
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        
        for (int i = 0; i < prod__Cosmet.size(); i++) {
            modelo2.addElement(prod__Cosmet.get(i).getNombre());
        }
        Main_Farmacia.cb_pC.setModel(modelo2);
        
        JOptionPane.showMessageDialog(this, "Se agregó");

        tf_idCosmetica.setText("");
        tf_nomCosmetica.setText("");
        tf_fCosmetica.setText("");
        tf_pcCosmetica.setText("");
        tf_pvCosmetica.setText("");
        rb_noCosmetica.setSelected(true);
        rb_siCosmetica.setSelected(false);
        js_unidCosmetica.setValue(0);
    }//GEN-LAST:event_btn_AgregarCosmeticaActionPerformed

    private void btn_agregarHigieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarHigieneActionPerformed
        String id3, nom3, fabrica3, tip3;
        double pCoste3, pVenta3;
        boolean esta3 = false;
        int unid3;

        id3 = tf_idHigiene.getText();
        nom3 = tf_nomHigiene.getText();
        fabrica3 = tf_fHigiene.getText();
        pCoste3 = Double.parseDouble(tf_pcHigiene.getText());
        pVenta3 = Double.parseDouble(tf_pvHigiene.getText());
        unid3 = (int) js_unidHigiene.getValue();

        if (rb_siHigiene.isSelected()) {
            esta3 = true;
            rb_noHigiene.setVisible(false);
        }
        if (rb_noHigiene.isSelected()) {
            esta3 = true;
            rb_siHigiene.setVisible(false);
        }

        tip3="Higiene";
        
        prod_Hig.add(new Prod_Higiene(tip3, id3, nom3, fabrica3, pCoste3, pVenta3, unid3, esta3));
        prod.add(new Productos(id3, nom3, fabrica3, pCoste3, pVenta3, unid3, esta3));
        System.out.println(prod);
        
        DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
        
        for (int i = 0; i < prod_Hig.size(); i++) {
            modelo3.addElement(prod_Hig.get(i).getNombre());
        }
        Main_Farmacia.cb_pH.setModel(modelo3);
        
        JOptionPane.showMessageDialog(this, "Se agregó");

        tf_idHigiene.setText("");
        tf_nomHigiene.setText("");
        tf_fHigiene.setText("");
        tf_pcHigiene.setText("");
        tf_pvHigiene.setText("");
        rb_noHigiene.setSelected(true);
        rb_siHigiene.setSelected(false);
        js_unidHigiene.setValue(0);
    }//GEN-LAST:event_btn_agregarHigieneActionPerformed

    private void btn_agregarInfantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarInfantilActionPerformed
        String id4, nom4, fabrica4, tip4;
        double pCoste4, pVenta4;
        boolean esta4 = false;
        int unid4;

        id4 = tf_idInfantil.getText();
        nom4 = tf_nomInfantil.getText();
        fabrica4 = tf_fInfantil.getText();
        pCoste4 = Double.parseDouble(tf_pcInfantil.getText());
        pVenta4 = Double.parseDouble(tf_pvInfantil.getText());
        unid4 = (int) js_unidInfantil.getValue();

        if (rb_siInfantil.isSelected()) {
            esta4 = true;
            js_noInfantil.setVisible(false);
        }
        if (js_noInfantil.isSelected()) {
            esta4 = true;
            rb_siInfantil.setVisible(false);
        }

        tip4="Infantil";
        prod_Infa.add(new Prod_Infantil(tip4, id4, nom4, fabrica4, pCoste4, pVenta4, unid4, esta4));
        prod.add(new Productos(id4, nom4, fabrica4, pCoste4, pVenta4, unid4, esta4));
        System.out.println(prod);
        
        DefaultComboBoxModel modelo4 = new DefaultComboBoxModel();
        
        for (int i = 0; i < prod_Infa.size(); i++) {
            modelo4.addElement(prod_Infa.get(i).getNombre());
        }
        Main_Farmacia.cb_pI.setModel(modelo4);
        
        JOptionPane.showMessageDialog(this, "Se agregó");

        tf_idInfantil.setText("");
        tf_nomInfantil.setText("");
        tf_fInfantil.setText("");
        tf_pcInfantil.setText("");
        tf_pvInfantil.setText("");
        js_noInfantil.setSelected(true);
        rb_siInfantil.setSelected(false);
        js_unidInfantil.setValue(0);
    }//GEN-LAST:event_btn_agregarInfantilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_cosmetica;
    private javax.swing.ButtonGroup bg_farmaciaCasa;
    private javax.swing.ButtonGroup bg_higiene;
    private javax.swing.ButtonGroup bg_infantil;
    private javax.swing.ButtonGroup bg_protegido;
    private javax.swing.JButton btn_AgregarCosmetica;
    private javax.swing.JButton btn_AgregarFCasa;
    private javax.swing.JButton btn_Casa;
    private javax.swing.JButton btn_Cosmetica;
    private javax.swing.JButton btn_Higiene;
    private javax.swing.JButton btn_Infantil;
    private javax.swing.JButton btn_agregarHigiene;
    private javax.swing.JButton btn_agregarInfantil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JDialog jd_Cosmetica;
    private javax.swing.JDialog jd_FarmaciaCasa;
    private javax.swing.JDialog jd_Higiene;
    private javax.swing.JDialog jd_Infantil;
    private javax.swing.JRadioButton js_noInfantil;
    private javax.swing.JSpinner js_unidCosmetica;
    private javax.swing.JSpinner js_unidHigiene;
    private javax.swing.JSpinner js_unidInfantil;
    private javax.swing.JSpinner js_unidadesCasa;
    private javax.swing.JRadioButton rb_noCasa;
    private javax.swing.JRadioButton rb_noCosmetica;
    private javax.swing.JRadioButton rb_noHigiene;
    private javax.swing.JRadioButton rb_siCasa;
    private javax.swing.JRadioButton rb_siCosmetica;
    private javax.swing.JRadioButton rb_siHigiene;
    private javax.swing.JRadioButton rb_siInfantil;
    private javax.swing.JTextField tf_fCosmetica;
    private javax.swing.JTextField tf_fHigiene;
    private javax.swing.JTextField tf_fInfantil;
    private javax.swing.JTextField tf_fabricanteCasa;
    private javax.swing.JTextField tf_idCosmetica;
    private javax.swing.JTextField tf_idHigiene;
    private javax.swing.JTextField tf_idInfantil;
    private javax.swing.JTextField tf_identificaCasa;
    private javax.swing.JTextField tf_nomCosmetica;
    private javax.swing.JTextField tf_nomHigiene;
    private javax.swing.JTextField tf_nomInfantil;
    private javax.swing.JTextField tf_nombreCasa;
    private javax.swing.JTextField tf_pCostoCasa;
    private javax.swing.JTextField tf_pVentaCasa;
    private javax.swing.JTextField tf_pcCosmetica;
    private javax.swing.JTextField tf_pcHigiene;
    private javax.swing.JTextField tf_pcInfantil;
    private javax.swing.JTextField tf_pvCosmetica;
    private javax.swing.JTextField tf_pvHigiene;
    private javax.swing.JTextField tf_pvInfantil;
    // End of variables declaration//GEN-END:variables

    ArrayList<Productos> prod = new ArrayList();
    ArrayList<Prod_FarmaciaCasa>prod_fCasa = new ArrayList();
    ArrayList<Prod_Cosmetica> prod__Cosmet = new ArrayList();
    ArrayList<Prod_Higiene> prod_Hig = new ArrayList();
    ArrayList<Prod_Infantil> prod_Infa = new ArrayList();

}
