/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bases2;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karen Medina
 */
public class Main_Farmacia extends javax.swing.JFrame {

    /**
     * Creates new form Main_Farmacia
     */
    public Main_Farmacia() {
        initComponents();
        Main_Laboratorio abrir = new Main_Laboratorio();
        abrir.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A_Prop = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_idPropietario = new javax.swing.JTextField();
        tf_nomPropietario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rb_siProp = new javax.swing.JRadioButton();
        rb_noProp = new javax.swing.JRadioButton();
        btn_AgregarPropietarios = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rb_siFarmac = new javax.swing.JRadioButton();
        rb_noFarmac = new javax.swing.JRadioButton();
        tf_idFarmaceutico = new javax.swing.JTextField();
        tf_nomFarmaceutico = new javax.swing.JTextField();
        btn_AgregarFarmaceuticos = new javax.swing.JButton();
        btn_AgregarFarmacia = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bg_responsableProp = new javax.swing.ButtonGroup();
        bg_responsableFarmac = new javax.swing.ButtonGroup();
        jd_RealizarPedidos = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        btn_Pedir = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_idC = new javax.swing.JTextField();
        tf_nC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_fC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        js_fCasa = new javax.swing.JSpinner();
        btn_GuardarFCasa = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_pcC = new javax.swing.JTextField();
        tf_pvC = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_idCosm = new javax.swing.JTextField();
        tf_nCosm = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        js_cantC = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        tf_fCosm = new javax.swing.JTextField();
        btn_guardarPedido_Cosmetica = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        tf_pcCosm = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_pvCosm = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_GuardarPedido_Infantil = new javax.swing.JButton();
        tf_idI = new javax.swing.JTextField();
        tf_nI = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_fI = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        js_cantI = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_pcI = new javax.swing.JTextField();
        tf_pvI = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_idH = new javax.swing.JTextField();
        tf_nH = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_fH = new javax.swing.JTextField();
        js_cantH = new javax.swing.JSpinner();
        btn_GuardarPedido_Higiene = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        tf_pcH = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_pvH = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_numIdenti = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_direComplet = new javax.swing.JTextArea();
        btn_agregarPropietarios = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Identificación:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("¿Es responsable?");

        bg_responsableProp.add(rb_siProp);
        rb_siProp.setSelected(true);
        rb_siProp.setText("Si");

        bg_responsableProp.add(rb_noProp);
        rb_noProp.setText("No");

        btn_AgregarPropietarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_AgregarPropietarios.setText("Agregar");
        btn_AgregarPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarPropietariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_idPropietario)
                            .addComponent(tf_nomPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_AgregarPropietarios)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(rb_siProp)))
                        .addGap(18, 18, 18)
                        .addComponent(rb_noProp)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_idPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nomPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_siProp)
                    .addComponent(rb_noProp))
                .addGap(30, 30, 30)
                .addComponent(btn_AgregarPropietarios)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Propietarios", jPanel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Identificación:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nombre:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("¿Es responsable?");

        bg_responsableFarmac.add(rb_siFarmac);
        rb_siFarmac.setSelected(true);
        rb_siFarmac.setText("Si");

        bg_responsableFarmac.add(rb_noFarmac);
        rb_noFarmac.setText("No");

        btn_AgregarFarmaceuticos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_AgregarFarmaceuticos.setText("Agregar");
        btn_AgregarFarmaceuticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarFarmaceuticosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_idFarmaceutico)
                            .addComponent(tf_nomFarmaceutico, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_AgregarFarmaceuticos)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(rb_siFarmac)))
                        .addGap(18, 18, 18)
                        .addComponent(rb_noFarmac)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_idFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nomFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb_siFarmac)
                    .addComponent(rb_noFarmac))
                .addGap(30, 30, 30)
                .addComponent(btn_AgregarFarmaceuticos)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Farmaceuticos", jPanel4);

        btn_AgregarFarmacia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_AgregarFarmacia.setText("Guardar Todo");
        btn_AgregarFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarFarmaciaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Realizar Pedidos");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout A_PropLayout = new javax.swing.GroupLayout(A_Prop.getContentPane());
        A_Prop.getContentPane().setLayout(A_PropLayout);
        A_PropLayout.setHorizontalGroup(
            A_PropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_PropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(A_PropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addGroup(A_PropLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_AgregarFarmacia)))
                .addContainerGap())
        );
        A_PropLayout.setVerticalGroup(
            A_PropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_PropLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addGap(18, 18, 18)
                .addGroup(A_PropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_AgregarFarmacia)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Realizar Perdido");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_Pedir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Pedir.setText("Pedir Producto");
        btn_Pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PedirActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Identificación:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Fabricante:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Unidades:");

        js_fCasa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btn_GuardarFCasa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_GuardarFCasa.setText("Guardar");
        btn_GuardarFCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarFCasaActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Precio costo:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Precio venta:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_pcC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_idC)
                                                .addComponent(tf_fC, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                            .addComponent(js_fCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_nC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_pvC))))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btn_GuardarFCasa)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(tf_idC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_fC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(tf_pvC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pcC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(js_fCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btn_GuardarFCasa)
                .addGap(39, 39, 39))
        );

        jTabbedPane3.addTab("Farmacia Casa", jPanel8);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Identificación:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Nombre:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Cantidad:");

        js_cantC.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Fabricante:");

        btn_guardarPedido_Cosmetica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_guardarPedido_Cosmetica.setText("Guardar");
        btn_guardarPedido_Cosmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarPedido_CosmeticaActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Precio costo:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Precio venta:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(tf_idCosm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_nCosm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_fCosm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel18))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(tf_pcCosm, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_pvCosm, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(js_cantC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btn_guardarPedido_Cosmetica)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(tf_idCosm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nCosm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_fCosm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_pcCosm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(tf_pvCosm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_cantC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(31, 31, 31)
                .addComponent(btn_guardarPedido_Cosmetica)
                .addGap(38, 38, 38))
        );

        jTabbedPane3.addTab("Cosmetica", jPanel9);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Identificación:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Nombre:");

        btn_GuardarPedido_Infantil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_GuardarPedido_Infantil.setText("Guardar");
        btn_GuardarPedido_Infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarPedido_InfantilActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Fabricante:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Cantidad:");

        js_cantI.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Precio costo:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Precio venta:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_cantI, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_idI)
                                    .addComponent(tf_fI)
                                    .addComponent(tf_pcI, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_pvI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btn_GuardarPedido_Infantil)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_idI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tf_nI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_fI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(tf_pcI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pvI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(js_cantI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn_GuardarPedido_Infantil)
                .addGap(38, 38, 38))
        );

        jTabbedPane3.addTab("Infantil", jPanel10);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Identificación:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Nombre:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Fabricante:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Cantidad:");

        js_cantH.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btn_GuardarPedido_Higiene.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_GuardarPedido_Higiene.setText("Guardar");
        btn_GuardarPedido_Higiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarPedido_HigieneActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("Precio costo:");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("Precio venta:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btn_GuardarPedido_Higiene)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_idH)
                                    .addComponent(tf_fH)
                                    .addComponent(tf_pcH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nH)
                                    .addComponent(tf_pvH, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(153, 153, 153))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(js_cantH, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(tf_idH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_fH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_pcH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(tf_pvH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(js_cantH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_GuardarPedido_Higiene)
                .addGap(39, 39, 39))
        );

        jTabbedPane3.addTab("Higiene", jPanel11);

        javax.swing.GroupLayout jd_RealizarPedidosLayout = new javax.swing.GroupLayout(jd_RealizarPedidos.getContentPane());
        jd_RealizarPedidos.getContentPane().setLayout(jd_RealizarPedidosLayout);
        jd_RealizarPedidosLayout.setHorizontalGroup(
            jd_RealizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RealizarPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_RealizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_RealizarPedidosLayout.createSequentialGroup()
                        .addComponent(jTabbedPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_RealizarPedidosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_RealizarPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Pedir)
                .addGap(237, 237, 237))
        );
        jd_RealizarPedidosLayout.setVerticalGroup(
            jd_RealizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_RealizarPedidosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3)
                .addGap(18, 18, 18)
                .addComponent(btn_Pedir)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Farmacia");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Número Identificación: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Dirección Completa: ");
        jLabel3.setToolTipText("");

        ta_direComplet.setColumns(20);
        ta_direComplet.setRows(5);
        jScrollPane1.setViewportView(ta_direComplet);

        btn_agregarPropietarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_agregarPropietarios.setText("Agregar Propietarios");
        btn_agregarPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPropietariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(tf_numIdenti))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregarPropietarios)
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_numIdenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btn_agregarPropietarios)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Info", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPropietariosActionPerformed
        A_Prop.setModal(true);
        A_Prop.pack();
        A_Prop.setLocationRelativeTo(A_Prop);
        A_Prop.setVisible(true);
    }//GEN-LAST:event_btn_agregarPropietariosActionPerformed

    private void btn_AgregarPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarPropietariosActionPerformed
        String id, nombr;
        boolean responsable = false;

        id = tf_idPropietario.getText();
        nombr = tf_nomPropietario.getText();

        if (rb_siProp.isSelected()) {
            responsable = true;
        }
        if (rb_noProp.isSelected()) {
            responsable = false;
        }

        listProp.add(new Persona_Propietario(responsable, nombr, id));
        JOptionPane.showMessageDialog(this, "Se agregó el Propietario");

        tf_idPropietario.setText("");
        tf_nomPropietario.setText("");
        rb_siProp.setSelected(true);
        rb_noProp.setSelected(false);
    }//GEN-LAST:event_btn_AgregarPropietariosActionPerformed

    private void btn_AgregarFarmaceuticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarFarmaceuticosActionPerformed
        String id2, nombr2;
        boolean responsable2 = false;

        id2 = tf_idFarmaceutico.getText();
        nombr2 = tf_nomFarmaceutico.getText();

        if (rb_siFarmac.isSelected()) {
            responsable2 = true;
        }
        if (rb_noFarmac.isSelected()) {
            responsable2 = false;
        }

        listFarmaceutico.add(new Persona_Farmaceutico(responsable2, nombr2, id2));
        JOptionPane.showMessageDialog(this, "Se agregó el Farmaceutico");

        tf_idFarmaceutico.setText("");
        tf_nomFarmaceutico.setText("");
        rb_siFarmac.setSelected(true);
        rb_noFarmac.setSelected(false);
    }//GEN-LAST:event_btn_AgregarFarmaceuticosActionPerformed

    private void btn_AgregarFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarFarmaciaActionPerformed
        String numID, direc;
        numID = tf_numIdenti.getText();
        direc = ta_direComplet.getText();

        listFarmacia.add(new Farmacia(numID, direc, listProp, listFarmaceutico));
        System.out.println(listFarmacia);

        tf_numIdenti.setText("");
        tf_nomFarmaceutico.setText("");
        ta_direComplet.setText("");
    }//GEN-LAST:event_btn_AgregarFarmaciaActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        jd_RealizarPedidos.setModal(true);
        jd_RealizarPedidos.pack();
        jd_RealizarPedidos.setLocationRelativeTo(jd_RealizarPedidos);
        jd_RealizarPedidos.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btn_GuardarFCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarFCasaActionPerformed
        String tip = "Farmacia_Casa";
        double pc, pv;
        pc = Double.parseDouble(tf_pcC.getText());
        pv = Double.parseDouble(tf_pvC.getText());
        cantida1 = (int) js_fCasa.getValue();
        prod_fCasa.add(new Prod_FarmaciaCasa(tip, tf_idC.getText(), tf_nC.getText(), tf_fC.getText(), pc, pv, cantida1, true));
        JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        System.out.println(prod_fCasa);

        tf_idC.setText("");
        tf_nC.setText("");
        tf_fC.setText("");
        tf_pcC.setText("");
        tf_pvC.setText("");
        js_fCasa.setValue(0);
    }//GEN-LAST:event_btn_GuardarFCasaActionPerformed

    private void btn_PedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PedirActionPerformed
        ped.add(new Pedido(prod_fCasa, cantida1, prod__Cosmet, cantida2, prod_Infa, cantida3, prod_Hig, cantida4));
        System.out.println(ped);
        JOptionPane.showMessageDialog(this, "Se está procesando...");

        try {
            // agregar a la tabla
            DefaultTableModel mod, mod1, mod2, mod3;
            mod = (DefaultTableModel) Main_Laboratorio.jTable1.getModel();
            Object[] newrow = new Object[mod.getColumnCount()];
            for (int i = 0; i < ped.size(); i++) {
                newrow[0] = ped.get(i).getListProduFCasa().get(i).getTipo();
                newrow[1] = ped.get(i).getListProduFCasa().get(i).getNombre();
                newrow[2] = ped.get(i).getListProduFCasa().get(i).getFabricante();
                newrow[3] = ped.get(i).getUnidFC();
            }
            mod.addRow(newrow);

            for (int i = 0; i < ped.size(); i++) {
                newrow[0] = ped.get(i).getListProduCosmetic().get(i).getTipo();
                newrow[1] = ped.get(i).getListProduCosmetic().get(i).getNombre();
                newrow[2] = ped.get(i).getListProduCosmetic().get(i).getFabricante();
                newrow[3] = ped.get(i).getUnidPC();
            }
            mod1 = (DefaultTableModel) Main_Laboratorio.jTable1.getModel();
            mod1.addRow(newrow);

            for (int i = 0; i < ped.size(); i++) {
                newrow[0] = ped.get(i).getListProdInfantil().get(i).getTipo();
                newrow[1] = ped.get(i).getListProdInfantil().get(i).getNombre();
                newrow[2] = ped.get(i).getListProdInfantil().get(i).getFabricante();
                newrow[3] = ped.get(i).getUnidI();
            }
            mod2 = (DefaultTableModel) Main_Laboratorio.jTable1.getModel();
            mod2.addRow(newrow);

            for (int i = 0; i < ped.size(); i++) {
                newrow[0] = ped.get(i).getListProdHigiene().get(i).getTipo();
                newrow[1] = ped.get(i).getListProdHigiene().get(i).getNombre();
                newrow[2] = ped.get(i).getListProdHigiene().get(i).getFabricante();
                newrow[3] = ped.get(i).getUnidH();
            }
            mod3 = (DefaultTableModel) Main_Laboratorio.jTable1.getModel();
            mod3.addRow(newrow);

            Main_Laboratorio.jTable1.setModel(mod);
            
            Main_Laboratorio.tf_pf.setText(Main_Farmacia.this.getName());
            
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_PedirActionPerformed

    private void btn_guardarPedido_CosmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarPedido_CosmeticaActionPerformed
        String tipo = "Cosmetica";
        double pC, pV;
        pC = Double.parseDouble(tf_pcCosm.getText());
        pV = Double.parseDouble(tf_pvCosm.getText());
        cantida2 = (int) js_cantC.getValue();
        prod__Cosmet.add(new Prod_Cosmetica(tipo, tf_idCosm.getText(), tf_nCosm.getText(), tf_fCosm.getText(), pC, pV, cantida2, true));
        JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        System.out.println(prod__Cosmet);

        tf_idCosm.setText("");
        tf_nCosm.setText("");
        tf_fCosm.setText("");
        tf_pcCosm.setText("");
        tf_pvCosm.setText("");
        js_cantC.setValue(0);
    }//GEN-LAST:event_btn_guardarPedido_CosmeticaActionPerformed

    private void btn_GuardarPedido_InfantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarPedido_InfantilActionPerformed
        String tipo3 = "Infantil";
        double pC3, pV3;
        pC3 = Double.parseDouble(tf_pcI.getText());
        pV3 = Double.parseDouble(tf_pvI.getText());
        cantida3 = (int) js_cantI.getValue();
        prod_Infa.add(new Prod_Infantil(tipo3, tf_idI.getText(), tf_nI.getText(), tf_fI.getText(), pC3, pV3, cantida3, true));
        JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        System.out.println(prod_Infa);

        tf_idI.setText("");
        tf_nI.setText("");
        tf_fI.setText("");
        tf_pcCosm.setText("");
        tf_pvCosm.setText("");
        js_cantI.setValue(0);

    }//GEN-LAST:event_btn_GuardarPedido_InfantilActionPerformed

    private void btn_GuardarPedido_HigieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarPedido_HigieneActionPerformed
        String tipo4 = "Higiene";
        double pC4, pV4;
        pC4 = Double.parseDouble(tf_pcH.getText());
        pV4 = Double.parseDouble(tf_pvH.getText());
        cantida4 = (int) js_cantH.getValue();
        prod_Hig.add(new Prod_Higiene(tipo4, tf_idH.getText(), tf_nH.getText(), tf_fH.getText(), pC4, pV4, cantida4, true));
        JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        System.out.println(prod_Hig);

        tf_idH.setText("");
        tf_nH.setText("");
        tf_fH.setText("");
        tf_pcH.setText("");
        tf_pvH.setText("");
        js_cantH.setValue(0);

    }//GEN-LAST:event_btn_GuardarPedido_HigieneActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Farmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog A_Prop;
    private javax.swing.ButtonGroup bg_responsableFarmac;
    private javax.swing.ButtonGroup bg_responsableProp;
    private javax.swing.JButton btn_AgregarFarmaceuticos;
    private javax.swing.JButton btn_AgregarFarmacia;
    private javax.swing.JButton btn_AgregarPropietarios;
    private javax.swing.JButton btn_GuardarFCasa;
    private javax.swing.JButton btn_GuardarPedido_Higiene;
    private javax.swing.JButton btn_GuardarPedido_Infantil;
    private javax.swing.JButton btn_Pedir;
    private javax.swing.JButton btn_agregarPropietarios;
    private javax.swing.JButton btn_guardarPedido_Cosmetica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JDialog jd_RealizarPedidos;
    private javax.swing.JSpinner js_cantC;
    private javax.swing.JSpinner js_cantH;
    private javax.swing.JSpinner js_cantI;
    private javax.swing.JSpinner js_fCasa;
    private javax.swing.JRadioButton rb_noFarmac;
    private javax.swing.JRadioButton rb_noProp;
    private javax.swing.JRadioButton rb_siFarmac;
    private javax.swing.JRadioButton rb_siProp;
    private javax.swing.JTextArea ta_direComplet;
    private javax.swing.JTextField tf_fC;
    private javax.swing.JTextField tf_fCosm;
    private javax.swing.JTextField tf_fH;
    private javax.swing.JTextField tf_fI;
    private javax.swing.JTextField tf_idC;
    private javax.swing.JTextField tf_idCosm;
    private javax.swing.JTextField tf_idFarmaceutico;
    private javax.swing.JTextField tf_idH;
    private javax.swing.JTextField tf_idI;
    private javax.swing.JTextField tf_idPropietario;
    private javax.swing.JTextField tf_nC;
    private javax.swing.JTextField tf_nCosm;
    private javax.swing.JTextField tf_nH;
    private javax.swing.JTextField tf_nI;
    private javax.swing.JTextField tf_nomFarmaceutico;
    private javax.swing.JTextField tf_nomPropietario;
    private javax.swing.JTextField tf_numIdenti;
    private javax.swing.JTextField tf_pcC;
    private javax.swing.JTextField tf_pcCosm;
    private javax.swing.JTextField tf_pcH;
    private javax.swing.JTextField tf_pcI;
    private javax.swing.JTextField tf_pvC;
    private javax.swing.JTextField tf_pvCosm;
    private javax.swing.JTextField tf_pvH;
    private javax.swing.JTextField tf_pvI;
    // End of variables declaration//GEN-END:variables

    ArrayList<Persona_Propietario> listProp = new ArrayList();
    ArrayList<Persona_Farmaceutico> listFarmaceutico = new ArrayList();
    ArrayList<Farmacia> listFarmacia = new ArrayList();
    ArrayList<Pedido> ped = new ArrayList();

    ArrayList<Prod_FarmaciaCasa> prod_fCasa = new ArrayList();
    int cantida1;
    //ArrayList<Prod_FarmaciaCasa> prod_fCasa2 = new ArrayList();

    ArrayList<Prod_Cosmetica> prod__Cosmet = new ArrayList();
    int cantida2;
    //ArrayList<Prod_Cosmetica> prod__Cosmet2 = new ArrayList();

    ArrayList<Prod_Higiene> prod_Hig = new ArrayList();
    int cantida4;
    //ArrayList<Prod_Higiene> prod_Hig2 = new ArrayList();

    ArrayList<Prod_Infantil> prod_Infa = new ArrayList();
    int cantida3;
    //ArrayList<Prod_Infantil> prod_Infa2 = new ArrayList();

    ArrayList<Productos> product = new ArrayList();
}
