/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bases2;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karen Medina
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_idProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_nProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_fProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_fc = new javax.swing.JRadioButton();
        rb_C = new javax.swing.JRadioButton();
        rb_I = new javax.swing.JRadioButton();
        rb_H = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tf_PC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_PV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        js_U = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        rb_SiP = new javax.swing.JRadioButton();
        rb_NoP = new javax.swing.JRadioButton();
        btn_AgregarProducto = new javax.swing.JButton();
        btn_ModificarProducto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tF_IDF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_DireccionF = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_idPropietario = new javax.swing.JTextField();
        tf_nomPropietario = new javax.swing.JTextField();
        btn_agregarPropietario = new javax.swing.JButton();
        btn_Modificar_Propietario = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_idFarmaceutico = new javax.swing.JTextField();
        tf_nomFarmaceutico = new javax.swing.JTextField();
        btn_AgregarFarmaceutico = new javax.swing.JButton();
        btn_Modificar_Farmaceutico = new javax.swing.JButton();
        btn_AgregarFarmacia = new javax.swing.JButton();
        btn_ModificarFarmacia = new javax.swing.JButton();
        btn_CrearPedido = new javax.swing.JButton();
        bg_protegido = new javax.swing.ButtonGroup();
        bg_tipo = new javax.swing.ButtonGroup();
        jd_pedidos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_idC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_nC = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_fC = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        js_unidadess = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        rb_pSi = new javax.swing.JRadioButton();
        rb_pNo = new javax.swing.JRadioButton();
        btn_GuardarPedidos = new javax.swing.JButton();
        btn_EnviarPedido = new javax.swing.JButton();
        bg_tipoPedido = new javax.swing.ButtonGroup();
        bg_protegidoPedido = new javax.swing.ButtonGroup();
        jd_laboratorio = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_vender = new javax.swing.JButton();
        panel_principal = new javax.swing.JPanel();
        btn_CREAR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_LABORATORIO = new javax.swing.JButton();

        jd_crear.setTitle("CREAR");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID producto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fabricante:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tipo:");

        bg_tipo.add(rb_fc);
        rb_fc.setSelected(true);
        rb_fc.setText("Farmacia_Casa");

        bg_tipo.add(rb_C);
        rb_C.setText("Cosmeticos");

        bg_tipo.add(rb_I);
        rb_I.setText("Infantil");

        bg_tipo.add(rb_H);
        rb_H.setText("Higiene");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Precio Costo:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Precio Venta:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Unidades:");

        js_U.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("¿Está protegido?");

        bg_protegido.add(rb_SiP);
        rb_SiP.setSelected(true);
        rb_SiP.setText("Si");

        bg_protegido.add(rb_NoP);
        rb_NoP.setText("No");

        btn_AgregarProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_AgregarProducto.setText("Agregar");
        btn_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarProductoActionPerformed(evt);
            }
        });

        btn_ModificarProducto.setText("Modificar");
        btn_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_fProd, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(tf_idProd))
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nProd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js_U, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addComponent(tf_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(rb_fc)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb_C)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_I)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_H))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_PV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(rb_SiP)
                                .addGap(18, 18, 18)
                                .addComponent(rb_NoP)))
                        .addGap(0, 85, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btn_AgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_ModificarProducto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_idProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_fProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_fc)
                    .addComponent(rb_C)
                    .addComponent(rb_I)
                    .addComponent(rb_H))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_PV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(rb_SiP)
                    .addComponent(rb_NoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarProducto)
                    .addComponent(btn_ModificarProducto))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Crear Producto", jPanel1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("ID Farmacia:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Dirección Completa:");

        ta_DireccionF.setColumns(20);
        ta_DireccionF.setRows(5);
        jScrollPane1.setViewportView(ta_DireccionF);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("FARMACIA");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Propietario");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Identificación:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nombre:");

        btn_agregarPropietario.setText("Agregar");
        btn_agregarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPropietarioActionPerformed(evt);
            }
        });

        btn_Modificar_Propietario.setText("Modificar");
        btn_Modificar_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_PropietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nomPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(tf_idPropietario)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btn_agregarPropietario)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Modificar_Propietario))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_idPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nomPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarPropietario)
                    .addComponent(btn_Modificar_Propietario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Farmacéutico");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Identificación:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Nombre:");

        btn_AgregarFarmaceutico.setText("Agregar");
        btn_AgregarFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarFarmaceuticoActionPerformed(evt);
            }
        });

        btn_Modificar_Farmaceutico.setText("Modificar");
        btn_Modificar_Farmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_FarmaceuticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_idFarmaceutico, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(tf_nomFarmaceutico))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btn_AgregarFarmaceutico)
                .addGap(18, 18, 18)
                .addComponent(btn_Modificar_Farmaceutico)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_idFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nomFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarFarmaceutico)
                    .addComponent(btn_Modificar_Farmaceutico))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btn_AgregarFarmacia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_AgregarFarmacia.setText("Agregar Farmacia");
        btn_AgregarFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarFarmaciaActionPerformed(evt);
            }
        });

        btn_ModificarFarmacia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ModificarFarmacia.setText("Modificar Farmacia");
        btn_ModificarFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarFarmaciaActionPerformed(evt);
            }
        });

        btn_CrearPedido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_CrearPedido.setText("Crear Pedido");
        btn_CrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(tF_IDF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btn_AgregarFarmacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ModificarFarmacia)
                .addGap(18, 18, 18)
                .addComponent(btn_CrearPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tF_IDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarFarmacia)
                    .addComponent(btn_ModificarFarmacia)
                    .addComponent(btn_CrearPedido))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Farmacia", jPanel2);

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField1.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ID Farmacia");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("ID Producto:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Nombre:");

        bg_tipoPedido.add(jRadioButton4);
        jRadioButton4.setText("Higiene");

        bg_tipoPedido.add(jRadioButton3);
        jRadioButton3.setText("Infantil");

        bg_tipoPedido.add(jRadioButton2);
        jRadioButton2.setText("Cosmeticos");

        bg_tipoPedido.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Farmacia_Casa");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Tipo:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Fabricante:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Unidades:");

        js_unidadess.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("¿Está protegido?");

        bg_protegidoPedido.add(rb_pSi);
        rb_pSi.setSelected(true);
        rb_pSi.setText("Si");

        bg_protegidoPedido.add(rb_pNo);
        rb_pNo.setText("No");

        btn_GuardarPedidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_GuardarPedidos.setText("Guardar");
        btn_GuardarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel22)
                        .addGap(28, 28, 28)
                        .addComponent(js_unidadess, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_pSi)
                                .addGap(18, 18, 18)
                                .addComponent(rb_pNo)))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_GuardarPedidos)
                .addGap(258, 258, 258))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_fC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton4)))
                            .addContainerGap(83, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_idC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel23))
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_nC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(js_unidadess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(rb_pSi)
                    .addComponent(rb_pNo))
                .addGap(71, 71, 71)
                .addComponent(btn_GuardarPedidos)
                .addGap(37, 37, 37))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tf_idC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(42, 42, 42)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(tf_fC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton4))
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        btn_EnviarPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_EnviarPedido.setText("Enviar Pedido");
        btn_EnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_pedidosLayout = new javax.swing.GroupLayout(jd_pedidos.getContentPane());
        jd_pedidos.getContentPane().setLayout(jd_pedidosLayout);
        jd_pedidosLayout.setHorizontalGroup(
            jd_pedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_pedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_EnviarPedido)
                .addGap(251, 251, 251))
        );
        jd_pedidosLayout.setVerticalGroup(
            jd_pedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_EnviarPedido)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Nombre", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btn_vender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_vender.setText("Vender");

        javax.swing.GroupLayout jd_laboratorioLayout = new javax.swing.GroupLayout(jd_laboratorio.getContentPane());
        jd_laboratorio.getContentPane().setLayout(jd_laboratorioLayout);
        jd_laboratorioLayout.setHorizontalGroup(
            jd_laboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_laboratorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jd_laboratorioLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btn_vender)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_laboratorioLayout.setVerticalGroup(
            jd_laboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_laboratorioLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_vender)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_CREAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CREAR.setText("CREAR");
        btn_CREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CREARActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("RESOLUCIÓN 1");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("RESOLUCIÓN 2");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("RESOLUCIÓN 3");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("RESOLUCIÓN 4");

        btn_LABORATORIO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_LABORATORIO.setText("LABORATORIO");
        btn_LABORATORIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LABORATORIOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_CREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(33, 33, 33)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LABORATORIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CREAR)
                    .addComponent(btn_LABORATORIO))
                .addGap(49, 49, 49)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(43, 43, 43)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CREARActionPerformed
        jd_crear.setModal(true);
        jd_crear.pack();
        jd_crear.setLocationRelativeTo(jd_crear);
        jd_crear.setVisible(true);
    }//GEN-LAST:event_btn_CREARActionPerformed

    private void btn_AgregarFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarFarmaciaActionPerformed
        String numID, direc;
        numID = tF_IDF.getText();
        direc = ta_DireccionF.getText();
        
        CrudFarmacia.create_farmacia(numID, direc, people, prod);

        listFarmacia.add(new Farmacia(numID, direc, listProp, listFarmaceutico));
        System.out.println(listFarmacia);

        JOptionPane.showMessageDialog(this, "Se agregó la Farmacia");

        tF_IDF.setText("");
        ta_DireccionF.setText("");
    }//GEN-LAST:event_btn_AgregarFarmaciaActionPerformed

    private void btn_AgregarFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarFarmaceuticoActionPerformed
        String id2, nombr2;

        id2 = tf_idFarmaceutico.getText();
        nombr2 = tf_nomFarmaceutico.getText();
        people.add(new Persona(nombr2, id2));
        listFarmaceutico.add(new Persona_Farmaceutico(nombr2, id2));
        JOptionPane.showMessageDialog(this, "Se agregó el Farmaceutico");

        tf_idFarmaceutico.setText("");
        tf_nomFarmaceutico.setText("");
    }//GEN-LAST:event_btn_AgregarFarmaceuticoActionPerformed

    private void btn_agregarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPropietarioActionPerformed
        String id, nombr;

        id = tf_idPropietario.getText();
        nombr = tf_nomPropietario.getText();
        
        people.add(new Persona(nombr, id));
        
        listProp.add(new Persona_Propietario(nombr, id));
        JOptionPane.showMessageDialog(this, "Se agregó el Propietario");

        tf_idPropietario.setText("");
        tf_nomPropietario.setText("");
    }//GEN-LAST:event_btn_agregarPropietarioActionPerformed

    private void btn_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarProductoActionPerformed
        String idp, nomP, fabricante, tipo = "";
        double precioC, precioV;
        int unidad;
        boolean protegido = false;

        if (rb_fc.isSelected()) {
            tipo = "Farmacia_Casa";
        }
        if (rb_C.isSelected()) {
            tipo = "Cosmeticos";
        }
        if (rb_I.isSelected()) {
            tipo = "Infantil";
        }
        if (rb_H.isSelected()) {
            tipo = "Higiene";
        }

        precioC = Double.parseDouble(tf_PC.getText());
        precioV = Double.parseDouble(tf_PV.getText());

        unidad = (int) js_U.getValue();

        if (rb_SiP.isSelected()) {
            protegido = true;
        }
        if (rb_NoP.isSelected()) {
            protegido = true;
        }
        
        pro = new Productos(tf_idProd.getText(), tf_nProd.getText(), tf_fProd.getText(), tipo, precioC, precioV, unidad, protegido);
        prod.add(new Productos(tf_idProd.getText(), tf_nProd.getText(), tf_fProd.getText(), tipo, precioC, precioV, unidad, protegido));
        System.out.println(prod);

        JOptionPane.showMessageDialog(this, "Se agregó el Producto");

        tf_idProd.setText("");
        tf_nProd.setText("");
        tf_fProd.setText("");
        rb_SiP.setSelected(true);
        rb_NoP.setSelected(false);
        rb_fc.setSelected(true);
        rb_C.setSelected(false);
        rb_I.setSelected(false);
        rb_H.setSelected(false);
        tf_PC.setText("");
        tf_PV.setText("");
        js_U.setValue(0);
    }//GEN-LAST:event_btn_AgregarProductoActionPerformed

    private void btn_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarProductoActionPerformed
        String idp, nomP, fabricante, tipo = "";
        double precioC, precioV;
        int unidad;
        boolean protegido = false;

        idp = tf_idProd.getText();
        nomP = tf_nProd.getText();
        fabricante = tf_fProd.getText();

        if (rb_fc.isSelected()) {
            tipo = "Farmacia_Casa";
        }
        if (rb_C.isSelected()) {
            tipo = "Cosmeticos";
        }
        if (rb_I.isSelected()) {
            tipo = "Infantil";
        }
        if (rb_H.isSelected()) {
            tipo = "Higiene";
        }

        precioC = Double.parseDouble(tf_PC.getText());
        precioV = Double.parseDouble(tf_PV.getText());

        unidad = (int) js_U.getValue();

        if (rb_SiP.isSelected()) {
            protegido = true;
        }
        if (rb_NoP.isSelected()) {
            protegido = true;
        }
        
        
        /*
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setIdentificación(idp);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setNombre(nomP);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setFabricante(fabricante);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setPrecioCosto(precioC);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setPrecioVenta(precioV);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setTipo(tipo);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setUnidades(unidad);
        ((Productos) prod.get(cb_productos.getSelectedIndex())).setEstaProtegido(protegido);
         */
        //prod.set(cb_productos.getSelectedIndex(), new Productos(tf_idProd.getText(), tf_nProd.getText(), tf_fProd.getText(), tipo, precioC, precioV, unidad, protegido));
        //System.out.println(prod);
        JOptionPane.showMessageDialog(this, "Se modificó éxitosamente el Producto");

        tf_idProd.setText("");
        tf_nProd.setText("");
        tf_fProd.setText("");
        rb_SiP.setSelected(true);
        rb_NoP.setSelected(false);
        rb_fc.setSelected(true);
        rb_C.setSelected(false);
        rb_I.setSelected(false);
        rb_H.setSelected(false);
        tf_PC.setText("");
        tf_PV.setText("");
        js_U.setValue(0);

    }//GEN-LAST:event_btn_ModificarProductoActionPerformed

    private void btn_ModificarFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarFarmaciaActionPerformed
        String numID, direc;
        numID = tF_IDF.getText();
        direc = ta_DireccionF.getText();

        try {
            CrudFarmacia.update_farmacia(numID, direc,pro);
        } catch (IOException ex) {
            Logger.getLogger(MENU.class.getName()).log(Level.SEVERE, null, ex);
        }
        //listFarmacia.set(cb_farmacia.getSelectedIndex(), new Farmacia(numID, direc, listProp, listFarmaceutico));
        System.out.println(listFarmacia);
        
        JOptionPane.showMessageDialog(this, "Se modificó la Farmacia");

        tF_IDF.setText("");
        ta_DireccionF.setText("");

    }//GEN-LAST:event_btn_ModificarFarmaciaActionPerformed

    private void btn_Modificar_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_PropietarioActionPerformed
        String id, nombr;

        id = tf_idPropietario.getText();
        nombr = tf_nomPropietario.getText();

        //people.add(new Persona(nombr, id));
        JOptionPane.showMessageDialog(this, "Se modificó el Propietario");

        tf_idPropietario.setText("");
        tf_nomPropietario.setText("");
    }//GEN-LAST:event_btn_Modificar_PropietarioActionPerformed

    private void btn_Modificar_FarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_FarmaceuticoActionPerformed
        String id2, nombr2;

        id2 = tf_idFarmaceutico.getText();
        nombr2 = tf_nomFarmaceutico.getText();

        //listFarmaceutico.add(new Persona_Farmaceutico(nombr2, id2));
        JOptionPane.showMessageDialog(this, "Se modificó el Farmaceutico");

        tf_idFarmaceutico.setText("");
        tf_nomFarmaceutico.setText("");
    }//GEN-LAST:event_btn_Modificar_FarmaceuticoActionPerformed

    private void btn_CrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearPedidoActionPerformed
        jd_pedidos.setModal(true);
        jd_pedidos.pack();
        jd_pedidos.setLocationRelativeTo(jd_pedidos);
        jd_pedidos.setVisible(true);
    }//GEN-LAST:event_btn_CrearPedidoActionPerformed

    private void btn_GuardarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarPedidosActionPerformed
        String tipo="", id;
        double pc, pv;
        int cantida;
        boolean protegido=false;
        id=tf_idC.getText();
        
        
        
        pc = 0.0;
        pv = 0.0;
        cantida = (int) js_unidadess.getValue();
        
        if (rb_fc.isSelected()) {
            tipo = "Farmacia_Casa";
        }
        if (rb_C.isSelected()) {
            tipo = "Cosmeticos";
        }
        if (rb_I.isSelected()) {
            tipo = "Infantil";
        }
        if (rb_H.isSelected()) {
            tipo = "Higiene";
        }
        
        if (rb_pSi.isSelected()) {
            protegido = true;
        }
        if (rb_pNo.isSelected()) {
            protegido = true;
        }

        prod.add(new Productos(id, tf_nC.getText(), tf_fC.getText(),tipo, pc, pv, cantida, protegido));
        JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        System.out.println(prod);

        tf_idC.setText("");
        tf_nC.setText("");
        tf_fC.setText("");
        js_unidadess.setValue(0);
    }//GEN-LAST:event_btn_GuardarPedidosActionPerformed

    private void btn_EnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarPedidoActionPerformed
        int cantida1;
        cantida1 = (int) js_unidadess.getValue();
        ped.add(new Pedido(prod,cantida1));
        System.out.println(ped);
        JOptionPane.showMessageDialog(this, "Se está procesando...");

        try {
            // agregar a la tabla
            DefaultTableModel mod, mod1, mod2, mod3;
            mod = (DefaultTableModel) jTable1.getModel();
            Object[] newrow = new Object[mod.getColumnCount()];
            for (int i = 0; i < ped.size(); i++) {
                newrow[0] = ped.get(i).getListProductoss().get(i).getTipo();
                newrow[1] = ped.get(i).getListProductoss().get(i).getNombre();
                newrow[2] = ped.get(i).getUnid();
            }
            mod.addRow(newrow);

        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btn_EnviarPedidoActionPerformed

    private void btn_LABORATORIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LABORATORIOActionPerformed
        jd_laboratorio.setModal(true);
        jd_laboratorio.pack();
        jd_laboratorio.setLocationRelativeTo(jd_pedidos);
        jd_laboratorio.setVisible(true);
    }//GEN-LAST:event_btn_LABORATORIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_protegido;
    private javax.swing.ButtonGroup bg_protegidoPedido;
    private javax.swing.ButtonGroup bg_tipo;
    private javax.swing.ButtonGroup bg_tipoPedido;
    private javax.swing.JButton btn_AgregarFarmaceutico;
    private javax.swing.JButton btn_AgregarFarmacia;
    private javax.swing.JButton btn_AgregarProducto;
    private javax.swing.JButton btn_CREAR;
    private javax.swing.JButton btn_CrearPedido;
    private javax.swing.JButton btn_EnviarPedido;
    private javax.swing.JButton btn_GuardarPedidos;
    private javax.swing.JButton btn_LABORATORIO;
    private javax.swing.JButton btn_ModificarFarmacia;
    private javax.swing.JButton btn_ModificarProducto;
    private javax.swing.JButton btn_Modificar_Farmaceutico;
    private javax.swing.JButton btn_Modificar_Propietario;
    private javax.swing.JButton btn_agregarPropietario;
    private javax.swing.JButton btn_vender;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_laboratorio;
    private javax.swing.JDialog jd_pedidos;
    private javax.swing.JSpinner js_U;
    private javax.swing.JSpinner js_unidadess;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JRadioButton rb_C;
    private javax.swing.JRadioButton rb_H;
    private javax.swing.JRadioButton rb_I;
    private javax.swing.JRadioButton rb_NoP;
    private javax.swing.JRadioButton rb_SiP;
    private javax.swing.JRadioButton rb_fc;
    private javax.swing.JRadioButton rb_pNo;
    private javax.swing.JRadioButton rb_pSi;
    private javax.swing.JTextField tF_IDF;
    private javax.swing.JTextArea ta_DireccionF;
    private javax.swing.JTextField tf_PC;
    private javax.swing.JTextField tf_PV;
    private javax.swing.JTextField tf_fC;
    private javax.swing.JTextField tf_fProd;
    private javax.swing.JTextField tf_idC;
    private javax.swing.JTextField tf_idFarmaceutico;
    private javax.swing.JTextField tf_idProd;
    private javax.swing.JTextField tf_idPropietario;
    private javax.swing.JTextField tf_nC;
    private javax.swing.JTextField tf_nProd;
    private javax.swing.JTextField tf_nomFarmaceutico;
    private javax.swing.JTextField tf_nomPropietario;
    // End of variables declaration//GEN-END:variables

    ArrayList<Productos> prod = new ArrayList();
    Productos pro = new Productos();
    ArrayList<Persona_Propietario> listProp = new ArrayList();
    ArrayList<Persona_Farmaceutico> listFarmaceutico = new ArrayList();
    ArrayList<Farmacia> listFarmacia = new ArrayList();
    ArrayList<Pedido> ped = new ArrayList();
    ArrayList<Persona> people = new ArrayList();

}
